// ============================================================
// Email delivery layer — Resend
// ============================================================

import { Resend } from 'resend';
import { generateSingleIcs } from './ics';
import type { EventItem } from './types';

// ---------------------------------------------------------------------------
// Client singleton
// ---------------------------------------------------------------------------

let _resend: Resend | null = null;

function getResend(): Resend | null {
  if (_resend) return _resend;

  const key = process.env.RESEND_API_KEY;
  if (!key) {
    console.warn('[email] RESEND_API_KEY not set — email delivery disabled');
    return null;
  }

  _resend = new Resend(key);
  return _resend;
}

function fromAddress(): string {
  return process.env.INVITE_FROM_EMAIL ?? 'invites@asx-calendar-api.vercel.app';
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Format an event date for display (e.g. "Mon 7 Apr 2026, 10:30 AEST"). */
function formatDate(event: EventItem): string {
  const d = new Date(event.event_date + 'T00:00:00');
  const day = d.toLocaleDateString('en-AU', {
    weekday: 'short',
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    timeZone: 'Australia/Sydney',
  });

  if (event.event_time) {
    return `${day}, ${event.event_time} AEST`;
  }
  return day;
}

// ---------------------------------------------------------------------------
// sendCalendarInvite
// ---------------------------------------------------------------------------

/**
 * Send a calendar invite email for a single event.
 *
 * Includes an ICS attachment so the recipient can add the event to their
 * calendar with one click.
 */
export async function sendCalendarInvite(
  toEmail: string,
  event: EventItem,
  unsubscribeUrl: string,
): Promise<boolean> {
  const resend = getResend();
  if (!resend) return false;

  const dateStr = formatDate(event);
  const title = event.title ?? `${event.ticker} ${event.event_type}`;
  const subject = `${event.ticker} ${title} — ${dateStr}`;

  // Build HTML body — minimal, terminal-light style
  const detailRows: string[] = [];
  detailRows.push(`<tr><td style="padding:4px 12px 4px 0;color:#666">Date</td><td>${dateStr}</td></tr>`);
  if (event.fiscal_period) {
    detailRows.push(`<tr><td style="padding:4px 12px 4px 0;color:#666">Period</td><td>${event.fiscal_period}</td></tr>`);
  }
  if (event.webcast_url) {
    detailRows.push(`<tr><td style="padding:4px 12px 4px 0;color:#666">Webcast</td><td><a href="${event.webcast_url}" style="color:#0066cc">${event.webcast_url}</a></td></tr>`);
  }
  if (event.phone_number) {
    let phoneStr = event.phone_number;
    if (event.phone_passcode) phoneStr += ` (passcode: ${event.phone_passcode})`;
    detailRows.push(`<tr><td style="padding:4px 12px 4px 0;color:#666">Dial-in</td><td>${phoneStr}</td></tr>`);
  }
  if (event.description) {
    detailRows.push(`<tr><td style="padding:4px 12px 4px 0;color:#666">Details</td><td>${event.description}</td></tr>`);
  }

  const html = `
<div style="font-family:'SF Mono',Menlo,Consolas,monospace;font-size:13px;line-height:1.6;color:#1a1a1a;max-width:600px;margin:0 auto;padding:24px">
  <div style="border-bottom:1px solid #e0e0e0;padding-bottom:12px;margin-bottom:16px">
    <strong style="font-size:15px">${event.ticker}</strong>
    <span style="color:#666;margin-left:8px">${event.company_name}</span>
  </div>

  <p style="margin:0 0 16px">${title}</p>

  <table style="border-collapse:collapse;font-size:13px;margin-bottom:20px">
    ${detailRows.join('\n    ')}
  </table>

  <p style="font-size:11px;color:#999;margin-top:24px;border-top:1px solid #e0e0e0;padding-top:12px">
    This invite was generated by ASX Calendar API.<br>
    <a href="${unsubscribeUrl}" style="color:#999">Unsubscribe</a>
  </p>
</div>`.trim();

  // Generate ICS attachment
  const icsContent = generateSingleIcs(event);
  const icsFilename = `${event.ticker}-${event.event_date}.ics`;

  try {
    await resend.emails.send({
      from: fromAddress(),
      to: toEmail,
      subject,
      html,
      headers: {
        'List-Unsubscribe': `<${unsubscribeUrl}>`,
        'List-Unsubscribe-Post': 'List-Unsubscribe=One-Click',
      },
      attachments: [
        {
          filename: icsFilename,
          content: Buffer.from(icsContent).toString('base64'),
          contentType: 'text/calendar',
        },
      ],
    });

    console.log(`[email] Sent calendar invite to ${toEmail} for ${event.ticker} ${event.event_date}`);
    return true;
  } catch (err) {
    console.error(`[email] Failed to send to ${toEmail}:`, err);
    return false;
  }
}

// ---------------------------------------------------------------------------
// sendWelcomeEmail
// ---------------------------------------------------------------------------

/**
 * Send a welcome / confirmation email after subscribing.
 */
export async function sendWelcomeEmail(
  toEmail: string,
  tickers: string[],
  feedUrl: string,
): Promise<boolean> {
  const resend = getResend();
  if (!resend) return false;

  const tickerList = tickers.map((t) => `<code>${t}</code>`).join(', ');

  const html = `
<div style="font-family:'SF Mono',Menlo,Consolas,monospace;font-size:13px;line-height:1.6;color:#1a1a1a;max-width:600px;margin:0 auto;padding:24px">
  <div style="border-bottom:1px solid #e0e0e0;padding-bottom:12px;margin-bottom:16px">
    <strong style="font-size:15px">ASX Calendar API</strong>
    <span style="color:#666;margin-left:8px">Subscription confirmed</span>
  </div>

  <p style="margin:0 0 12px">Your watchlist has been set up. You will receive calendar invites as events are confirmed for:</p>

  <p style="margin:0 0 16px;padding:8px 12px;background:#f5f5f5;border-radius:4px">${tickerList}</p>

  <p style="margin:0 0 8px"><strong>Your personal calendar feed:</strong></p>
  <p style="margin:0 0 16px;padding:8px 12px;background:#f5f5f5;border-radius:4px;word-break:break-all">
    <a href="${feedUrl}" style="color:#0066cc">${feedUrl}</a>
  </p>

  <p style="margin:0 0 4px;color:#666;font-size:12px">Add this URL to your calendar app to stay in sync:</p>
  <ul style="margin:0 0 16px;padding-left:20px;font-size:12px;color:#666">
    <li><strong>Outlook:</strong> Open Calendar &rarr; Add calendar &rarr; From internet</li>
    <li><strong>Google Calendar:</strong> Other calendars (+) &rarr; From URL</li>
    <li><strong>Apple Calendar:</strong> File &rarr; New Calendar Subscription</li>
  </ul>

  <p style="font-size:11px;color:#999;margin-top:24px;border-top:1px solid #e0e0e0;padding-top:12px">
    This email was sent by ASX Calendar API.
  </p>
</div>`.trim();

  try {
    await resend.emails.send({
      from: fromAddress(),
      to: toEmail,
      subject: `ASX Calendar — Subscribed to ${tickers.length} ticker${tickers.length === 1 ? '' : 's'}`,
      html,
    });

    console.log(`[email] Sent welcome email to ${toEmail}`);
    return true;
  } catch (err) {
    console.error(`[email] Failed to send welcome to ${toEmail}:`, err);
    return false;
  }
}
